const Map<String, String> arabic = {
  'english ': '      اللغه الانجليزية ',
  "arabic ": "         اللغه العربيه ",
  'language': 'اللغة',
  'theme': 'السمات',
  'Settings': 'الاعدادات',
  'Dark Mode': 'الوضع الداكن',
  'About Developers>': 'حول المطورين>',
  'temperature': 'درجة حرارة',
  'Degrees': 'درجات',
  'Measure': '    قيس ',
  'online': 'متصل',
  'offline': 'غير متصل',
  'Oxygen Ratio': 'نسبه الاكسجين',
  'Heart Rate': 'معدل ضربات القلب',
  'Heart AVG bpm': 'متوسط معدل ضربات القلب',
  'click to see report': 'انقر لرؤية التقرير',
  'Login': 'تسجيل الدخول',
  'Email Address': 'عنوان البريد الإلكتروني',
  'Password': 'كلمة المرور',
  'Remember password': 'إعادة تذكر كلمة المرور',
  'select language': 'اختار اللغة',
   "Electronic Human Limbs": "الأطراف الإصطناعية الذكية",
  'Please enter your password': 'من فضلك أدخل رقمك السري',
  'Enter your Password': 'ادخل رقمك السري',
  'Please enter your email': 'رجاءا أدخل بريدك الإلكتروني',
  'Enter your email': "أدخل بريدك الإلكتروني",
  "Please Login to continue": "الرجاء تسجيل الدخول للمتابعة",
  'oxygen': 'الاكسجين',
  'heart': 'القلب',
  'temp': 'الحراره',
  'setting': 'الاعدادات',
  'chat': 'المحادثه'
};
