const Map<String, String> en_US = {
  'English': 'English',
  'Arabic': 'Arabic',
  'language': 'language',
  'theme': 'theme',
  'Settings': 'Settings',
  'light': 'light',
  'Dark Mode': 'Dark Mode',
  'About Developers>': 'About Developers>',
  'temperature': 'temperature',
  'Degrees': 'Degrees',
  'Measure': 'Measure',
  'online': 'online',
  'offline': 'offline',
  'Oxygen Ratio': 'Oxygen Ratio',
  'Heart Rate': 'Heart Rate',
  'Heart AVG bpm': 'Heart AVG bpm',
  'click to see report': 'click to see report',
  'Login': 'Login',
  'Email Address': 'Email Address',
  'Password': 'Password',
  'Remember password': 'Remember password',
  'Electronic Human Limbs': 'Electronic Human Limbs',
  'select language': 'select language',
 'Please enter your password':'Please enter your password',
 'Enter your Password':'Enter your Password',
 'Please enter your email':'Please enter your email',
 'Enter your email':'Enter your email',
 "Please Login to continue":"Please Login to continue",
'oxygen':'oxygen',
'heart':'heart',
'temp':'temp',
'setting':'setting',
'chat':'chat'
};
